<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>2</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <!-- <GenerateAssemblyInfo>false</GenerateAssemblyInfo> -->
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>False</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Version></Version>
    <Authors>FSofT</Authors>
    <Product>GpxViewer</Product>
    <Copyright>Copyright © FSofT 4/2020</Copyright>
    <Description>25.9.2025</Description>
    <Title>Title</Title>
    <PackageProjectUrl></PackageProjectUrl>
    <PackageReleaseNotes>Versionshinweis</PackageReleaseNotes>
    <AssemblyVersion></AssemblyVersion>
    
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
    <GenerateResourceWarnOnBinaryFormatterUse>false</GenerateResourceWarnOnBinaryFormatterUse>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\bin\Debug\</OutputPath>
    <NoWarn>IDE1006</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\bin\Release\</OutputPath>
    <NoWarn>IDE1006</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>prog.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>
    </AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestCertificateThumbprint>29A66FD81CC85710B9C9EE9D75552BAF2E1500B6</ManifestCertificateThumbprint>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestKeyFile>GpxViewer_TemporaryKey.pfx</ManifestKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateManifests>true</GenerateManifests>
  </PropertyGroup>
  <PropertyGroup>
    <SignManifests>false</SignManifests>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="EditableGpxControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="NumericUpDownMenuItem.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="PictureEdit\PictureManager.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="ReadOnlyGpxControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="TreeViewExt.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Unclassified.UI\ColorFader.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Unclassified.UI\ColorField.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Unclassified.UI\ColorWheel.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Unclassified.UI\SpecColorSelector.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Images\reload.png" />
    <EmbeddedResource Include="Images\zoom1.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Images\CursorMarker.cur" />
    <Content Include="Images\CursorRemove.cur" />
    <Content Include="Images\CursorSplit.cur" />
    <Content Include="Images\FlagBlue.png" />
    <Content Include="Images\FlagGreen.png" />
    <Content Include="Images\FlagRed.png" />
    <Content Include="Images\Foto.png" />
    <Content Include="Images\garmin1.png" />
    <Content Include="Images\garmin2.png" />
    <EmbeddedResource Include="Images\Prog.png" />
    <Content Include="prog.ico" />
    <Content Include="Images\PinBlue.png" />
    <Content Include="Images\PinGreen.png" />
    <Content Include="Images\PinRed.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\exiflibrary\ExifLibrary\ExifLibrary.csproj" />
    <ProjectReference Include="..\FSofTUtils\FSofTUtils.csproj" />
    <ProjectReference Include="..\GarminImageCreator\GarminImageCreator.csproj" />
    <ProjectReference Include="..\GMap.NET\GMap.NET.Core\GMap.NET.Core.csproj" />
    <ProjectReference Include="..\SpecialMapCtrl\SpecialMapCtrl.csproj" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.7.2">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.7.2 %28x86 und x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.9" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="ExtMarker.cs" />
    <Compile Remove="MapControlHelper.cs" />
    <Compile Remove="MyCustomToolStripControlHost.cs" />
    <Compile Remove="sqlitetest.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="gpx-tracks.xml" />
    <None Remove="Images\Mapsource-Png.zip" />
  </ItemGroup>
  <ItemGroup>
    <None Update="gpxviewer.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Prog.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <PropertyGroup>
    <ContentSQLiteInteropFiles>true</ContentSQLiteInteropFiles>
    <CopySQLiteInteropFiles>true</CopySQLiteInteropFiles>
    <CleanSQLiteInteropFiles>false</CleanSQLiteInteropFiles>
    <CollectSQLiteInteropFiles>false</CollectSQLiteInteropFiles>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <PackageIcon>Prog.png</PackageIcon>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>